# Generated by Django 5.0.14 on 2026-04-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cashier', 'Cashier'), ('captain', 'Captain'), ('waiter', 'Waiter'), ('chef', 'Chef'), ('customer', 'Customer')], default='cashier', max_length=20),
        ),
    ]
