# Generated by Django 5.0.14 on 2026-04-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='height',
            field=models.IntegerField(default=100, help_text='Height in pixels'),
        ),
        migrations.AddField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('square', 'Square'), ('rectangle', 'Rectangle'), ('circle', 'Circle')], default='square', max_length=20),
        ),
        migrations.AddField(
            model_name='table',
            name='width',
            field=models.IntegerField(default=100, help_text='Width in pixels'),
        ),
        migrations.AddField(
            model_name='table',
            name='x_pos',
            field=models.IntegerField(default=0, help_text='X position in percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='table',
            name='y_pos',
            field=models.IntegerField(default=0, help_text='Y position in percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='floorsection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
