# Generated by Django 5.0.14 on 2026-04-17 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_table_height_table_shape_table_width_table_x_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='qr_code_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
