# Generated by Django 5.0.14 on 2026-04-17 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_table_qr_code_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorDecor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('decor_type', models.CharField(choices=[('plant', 'Plant / Greenery'), ('wall', 'Wall / Partition'), ('counter', 'Counter / Bar'), ('pillar', 'Pillar')], default='plant', max_length=20)),
                ('shape', models.CharField(choices=[('square', 'Square'), ('rectangle', 'Rectangle'), ('circle', 'Circle')], default='square', max_length=20)),
                ('x_pos', models.IntegerField(default=0)),
                ('y_pos', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=50)),
                ('height', models.IntegerField(default=50)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decor_items', to='tables.floorsection')),
            ],
        ),
    ]
