# Generated by Django 5.0.14 on 2026-04-17 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_floordecor'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='attached_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='tables.table'),
        ),
    ]
