# Generated by Django 5.0.14 on 2026-04-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_id_alter_menuitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kitchen_station',
            field=models.CharField(choices=[('kitchen', 'Main Kitchen'), ('bar', 'Bar / Drinks'), ('pantry', 'Pantry / Desserts'), ('tandoor', 'Tandoor / Oven')], default='kitchen', max_length=20),
        ),
    ]
