# Generated by Django 5.0.14 on 2026-04-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_customer_name_order_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
