# Generated by Django 5.0.14 on 2026-04-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_status'),
        ('tables', '0005_table_attached_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_tables',
            field=models.ManyToManyField(blank=True, related_name='joined_orders', to='tables.table'),
        ),
    ]
